version: "3.2"

services:
  raspitemperaturelogger:
    build:
      context: .
      dockerfile: Dockerfile
    image: raspitemperaturelogger
    container_name: raspitemperaturelogger
    restart: always
    volumes:
      - /sys/class/thermal:/sys/class/thermal
    environment:
      - DB_HOST="localhost"
      - DB_USER="admin"
      - DB_PASS="admin"
    external_links:
      - influxdb
